[2024-12-29T18:03:32.454+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T18:03:32.472+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T18:03:32.474+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-29T18:03:32.546+0000] {taskinstance.py:2217} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-12-28 00:00:00+00:00
[2024-12-29T18:03:32.575+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-12-29T18:03:32.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'postgres_jaffle_to_snowflake', 'airbyte_check_sync', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/postgres_jaffle_to_snowflake.py', '--cfg-path', '/tmp/tmpspn0029k']
[2024-12-29T18:03:32.604+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask airbyte_check_sync
[2024-12-29T18:03:32.858+0000] {task_command.py:423} INFO - Running <TaskInstance: postgres_jaffle_to_snowflake.airbyte_check_sync scheduled__2024-12-28T00:00:00+00:00 [running]> on host a68ea757822e
[2024-12-29T18:03:33.113+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_jaffle_to_snowflake' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2024-12-29T18:03:33.135+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-29T18:03:33.180+0000] {airbyte.py:104} INFO - Waiting for job 63 to complete.
[2024-12-29T18:04:33.582+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-29T18:04:36.238+0000] {airbyte.py:104} INFO - Waiting for job 63 to complete.
[2024-12-29T18:05:36.321+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-29T18:05:36.922+0000] {airbyte.py:104} INFO - Waiting for job 63 to complete.
[2024-12-29T18:06:36.989+0000] {base.py:83} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-12-29T18:06:37.524+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 110, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 91, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2024-12-29T18:06:37.589+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_jaffle_to_snowflake, task_id=airbyte_check_sync, execution_date=20241228T000000, start_date=20241229T180332, end_date=20241229T180637
[2024-12-29T18:06:37.830+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task airbyte_check_sync (Job failed: 
<Response [200]>; 86)
[2024-12-29T18:06:37.975+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-29T18:06:38.342+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
